#' Clustered Recurrent-Time Dataset: crt_dt
#'
#' A simulated dataset of clustered recurrent events with terminal/censoring
#' outcomes and covariates, suitable for examples and tests.
#'
#' @format A data frame with the following columns:
#' \describe{
#'   \item{id}{Integer subject ID (within the whole sample).}
#'   \item{cluster}{Integer cluster ID.}
#'   \item{time}{Numeric event/censoring time.}
#'   \item{status}{Integer event type indicator:
#'                \code{0} = censored,
#'                \code{1} = recurrent type 1,
#'                \code{2} = recurrent type 2,
#'                \code{3} = death (terminal).}
#'   \item{trt}{Cluster-level treatment indicator carried to subjects (e.g., 0/1).}
#'   \item{Z1}{Numeric covariate.}
#'   \item{Z2}{Numeric covariate.}
#' }
#'
#' @details
#' Rows represent observed events (including censoring and death) for each subject.
#' Multiple rows per \code{id} indicate multiple recurrent events; terminal/censoring
#' rows mark the end of observation for that subject.
#'
#' @usage data(crt_dt)
#' @source Generated by the package's simulation utilities.
#' @examples
#' data(crt_dt)
#' head(crt_dt)
"crt_dt"
