#' Individual Recurrent-Time Dataset: irt_dt
#'
#' A simulated dataset of recurrent events with terminal/censoring outcomes
#' and covariates, organized in long format.
#'
#' @format A data frame with the following columns:
#' \describe{
#'   \item{id}{Integer subject ID (within the whole sample).}
#'   \item{cluster}{Integer cluster ID.}
#'   \item{time}{Numeric event/censoring time.}
#'   \item{status}{Integer event type indicator:
#'                \code{0} = censored,
#'                \code{1} = recurrent type 1,
#'                \code{2} = recurrent type 2,
#'                \code{3} = death (terminal).}
#'   \item{trt}{Cluster-level treatment indicator carried to subjects (e.g., 0/1).}
#'   \item{Z1}{Numeric covariate.}
#'   \item{Z2}{Numeric covariate.}
#' }
#'
#' @details
#' Long-format events: each row is an event (or censoring/death) for a subject.
#'
#' @usage data(irt_dt)
#' @source Generated by the package's simulation utilities.
#' @examples
#' data(irt_dt)
#' head(irt_dt)
"irt_dt"
